[DPK] Add functions to accommodate device public key.
google/webauthndemo pull request #105
Opened 2022-08-08 05:57 UTC by weiilug

1. Add function to store dpk in a separate collection ('dpk') of firestore.
2. Add function to retrieve dpks.
3. Complement the removeCredential function to remove the related dpks as well.
4. Update the main.ts to show the dpk list for each credential

2022-08-08 12:07 UTC, agektmr requested changes

2022-08-08 12:07 UTC, agektmr commented on src/libs/credential.ts
> +  for (var cred of results) {
Let's not use `var`

```suggestion
  for (let cred of results) {
```

2022-08-08 12:07 UTC, agektmr commented on src/libs/credential.ts
> +  let results: StoredCredential[] = [];
No need to use `let`

```suggestion
  const results: StoredCredential[] = [];
```

2022-08-08 12:08 UTC, agektmr commented on src/libs/webauthn.ts
> +      const {dpk} = authenticationInfo.authenticatorExtensionResults.devicePublicKey;
This is just my personal convention. Never checked the style guide.

2022-08-09 04:52 UTC, weiilug commented on src/libs/webauthn.ts
> +      const {dpk} = authenticationInfo.authenticatorExtensionResults.devicePublicKey;
Okay, it's also reasonable to follow your convention. Just feel free to let me know anything I just missed. Thanks!

2022-08-12 11:05 UTC, agektmr requested changes

2022-08-12 11:05 UTC, agektmr commented on src/public/scripts/main.ts
> +            <dt>Device Public Key</dt>
Can you make this section conditional?

2022-08-15 05:18 UTC, merged