Removed allow credentials checkbox and updated the exclude credentials check box
google/webauthndemo pull request #95
Opened 2022-03-22 09:33 UTC by weiilug

This updates includes:

1. removed the allow credentials check box and the logic on collect options
2. added back the checkbox for each card
3. updated the new added card isChecked status dependent on the `exclude all credentials` checkbox

2022-03-22 10:06 UTC, agektmr requested changes
Made some comments.

2022-03-22 21:58 UTC, weiilug commented on src/templates/partials/sidebar.html
> +  <!-- <mwc-formfield
This check box is recovered for the new revision.

2022-03-22 21:59 UTC, weiilug commented on src/public/scripts/main.ts
> + const onToggleCheckboxes = (e: any): void => {
onExcludeAllCredentials() added

2022-03-22 21:59 UTC, weiilug commented on src/public/scripts/main.ts
> +    //if (!$('#empty-allow-credentials').checked) {
this checkbox is recovered.

2022-03-23 00:56 UTC, agektmr approved these changes
LGTM

2022-03-23 00:56 UTC, merged